name: One

on:
  - push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          mkdir -p out
          echo "Hello world one!" > out/index.html
      - uses: actions/checkout@v4
        with:
          path: pages
      - run: |
          cd pages
          git checkout -b pages
          rm -rf one
          cp -r ../out one
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push -u origin pages
